build.gradle, src/main/java/goorm/eagle7/stelligence/common/merge/MergeService.java, src/main/java/goorm/eagle7/stelligence/common/merge/handler/AmendmentMergeTemplate.java, src/main/java/goorm/eagle7/stelligence/common/merge/handler/AmendmentMergeTemplateMapper.java, src/main/java/goorm/eagle7/stelligence/common/merge/handler/CreateAmendmentMergeTemplate.java, src/main/java/goorm/eagle7/stelligence/common/merge/handler/DeleteAmendmentMergeTemplate.java, src/main/java/goorm/eagle7/stelligence/common/merge/handler/UpdateAmendmentMergeTemplate.java, src/main/java/goorm/eagle7/stelligence/domain/amendment/model/Amendment.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/model/Contribute.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/model/ContributeStatus.java, src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java, src/test/java/goorm/eagle7/stelligence/common/merge/MergeServiceIntegratedTest.java
- DocumentService의 mergeContribute를 별도의 서비스로 옮겼습니다.
- 주요 사항은 다음과 같습니다.
- MergeService 개발 : MergeService는 배치로부터 호출되어 수정안을 반영하는 역할을 합니다.
- AmendmentMergeTemplate : 각각의 반영에 대해 공통적인 역할과 수정안 타입에 따른 세부적인 역할을 분리할 수 있도록 합니다. 또한 각각의 반영에 대한 코드를 분리하여 가독성을 높였고 추후 타입 추가에 대해 열려있게 만들었습니다.
- 필요에 의해 Contribute 엔티티를 생성했습니다.
- 필요에 의해 Amendment 엔티티에 코드를 추가했습니다. 은지님은 확인하신 뒤 머지 부탁드립니다.
=> 15 amendment 반영 서비스 개발

src/test/java/goorm/eagle7/stelligence/common/entity/BaseTimeEntityTest.java, src/test/java/goorm/eagle7/stelligence/domain/section/SectionRepositoryTest.java, src/test/resources/dummy.sql
- @DataJpaTest시 자동으로 H2를 사용하는데, 이 때에 dialect 때문에 에러가 발생했던 것을 파악했습니다.
- 아래 내용을 반영한 뒤 @DataJpaTest가 적절한 테스트에는 @DataJpaTest를 반영해 주었습니다.
- dummy.sql에 into가 빠져있었던 부분을 수정했습니다.
- 테스트의 application.properties에 혹시 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect 가 있다면 삭제하면 좋을 것 같습니다.
closes #26
=> 26 datajpatest h2 error

src/main/java/goorm/eagle7/stelligence/api/DatabaseConnectionApplicationRunner.java, src/main/java/goorm/eagle7/stelligence/domain/document/graph/DocumentGraphService.java, src/main/java/goorm/eagle7/stelligence/domain/document/graph/DocumentNodeRepository.java, src/main/java/goorm/eagle7/stelligence/domain/document/graph/dto/DocumentNodeResponse.java, src/test/java/goorm/eagle7/stelligence/domain/document/graph/DocumentGraphServiceTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/graph/DocumentNodeRepositoryTest.java
- 제목으로 노드를 검색하는 기능을 추가했습니다.  (문서 별 반짝반짝이나, 글 작성시 링크 연결 등에 사용 예정)
- 위 기능을 안정적으로 지원하기 위해 애플리케이션 실행 시점에 검색을 위한 인덱스 설정이 완료되어있는지 확인합니다.
- 문서 id들로 노드를 검색하는 기능을 추가했습니다. (DocumentContentService와 연계하여 내용으로 검색에 활용)
- 추후 비즈니스 요구사항에 따라 제목 검색 방식이 부분 일치 검색(*)이 아닌, 유사도 기반 검색(~)으로 변경될 수 있습니다.
- 추후 제목 검색에 활용된 fulltext index의 옵션을 eventually_consistent로 설정하게 될 수 있습니다.
- 이때는 노드 생성/수정에 대해 인덱스가 즉시 반영되지 않지만, 가용성을 높일 수 있어서 잘 고려해봐야할 것 같습니다.
closes #
=> 28 문서 그래프에서 제목으로 문서 검색 기능

src/main/java/goorm/eagle7/stelligence/domain/document/content/dto/DocumentResponse.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/dto/SectionResponse.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/parser/SectionResponseConcatenator.java, src/main/java/goorm/eagle7/stelligence/domain/section/model/Heading.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentServiceReadTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/parser/SectionResponseConcatenatorTest.java, src/test/resources/dummy.sql
- 이제는 DocumentResponse에서 전체 문서 내용을 하나의 문자열로 조회할 수 있습니다.
- DocumentResponse에 content 필드를 추가했습니다.
- content 필드에 들어가는 내용을 만들 SectionResponseConcatenator를 개발했습니다.
- 관련 테스트코드를 작성했습니다.
- 
closes #60
=> 60 document api markdown text

src/main/java/goorm/eagle7/stelligence/domain/document/DocumentController.java, src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/model/Document.java, src/main/java/goorm/eagle7/stelligence/domain/document/dto/DocumentCreateRequest.java, src/main/java/goorm/eagle7/stelligence/domain/member/model/Member.java, src/test/java/goorm/eagle7/stelligence/config/mockdata/TestFixtureGenerator.java, src/test/java/goorm/eagle7/stelligence/domain/document/DocumentServiceTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentMergeConcurrencyTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentServiceCreateTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/graph/DocumentFacadeServiceGraphTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/graph/DocumentGraphServiceTest.java
- 이제는 Document 생성시 Member를 함께 저장합니다.
- Document 조회시 최초 작성자 정보를 제공하는 기능은 이후의 이슈에서 처리할 예정입니다.
- Document의 정적팩토리 메서드가 멤버를 받도록 하고, Controller로부터 loginId를 받아야 했기 때문에 굉장히 많은 클래스가 수정되었습니다.
- 많은 클래스가 수정되었기 때문에 빠르게 로컬에 붙이고 개발 이어가시면 좋을 것 같습니다.
- 영민님 테스트 코드를 수정한 부분이 있습니다. (service의 파라미터 변경 - loginId 추가)
- 한나님 Member Entity를 수정한 부분이 있습니다. (incrementContributes 메서드 작성)
closes #64
=> 64 document section member

src/main/java/goorm/eagle7/stelligence/common/auth/memberinfo/MemberInfo.java
- Swagger의 글 생성 API의 RequestBody에 MemberInfo가 요청값으로 나타나는 문제를 해결했습니다.
- @Sooamazing 코드 수정했으니 확인해주세요.
closes #83
=> bug: MemberInfo가 Swagger에 RequestBody로 나타나는 문제 해결

src/main/java/goorm/eagle7/stelligence/domain/amendment/AmendmentService.java, src/main/java/goorm/eagle7/stelligence/domain/section/SectionRepository.java, src/test/java/goorm/eagle7/stelligence/domain/section/SectionRepositoryTest.java
- 이제는 SectionRepository.findLatestSection이 Optional을 반환합니다.
- AmendmentService에서 findLatestSection을 사용하는 부분을 수정했습니다. @eenzzi  확인해주세용
closes #81
=> 81 SectionRepository.findLatestSection이 Optional을 반환

docker-compose-local.yml, src/main/java/goorm/eagle7/stelligence/domain/document/graph/DocumentGraphService.java
- 문서 그래프를 조회할 때 캐싱을 적용하였습니다.
- 자주 조회되지 않을 데이터를 캐싱하는 것은 비효율적입니다.
- 루트 노드로부터 조회 or 전체 조회할 때만 캐싱을 적용하였습니다.
- docker-compose-local.yml에 redis의 maxmemory를 500mb로 제한하는 코드를 추가하였습니다. (1gb 등 설정 변경 가능)
- docker-compose-local.yml에 redis의 희생자 선정 알고리즘을 volatile-lru로 설정하였습니다. (volatile-lfu 등 설정 변경 가능)
- volatile-lru: expire가 설정된 캐시들 중, 가장 오래전에 조회된 캐시를 희생시킵니다.
- docker-compose -f docker-compose-local.yml up --build -d 로 다시 빌드해주세요
closes #
=> 78 문서 그래프 캐시 적용

src/main/java/goorm/eagle7/stelligence/api/log/RequestCachingFilter.java, src/main/java/goorm/eagle7/stelligence/api/log/RequestLoggingFilter.java
- 이제는 REQUEST URI 로그에서 파라미터가 없을 때 ?가 찍히지 않습니다.
- 이제는 REQUEST BODY 로그가 너무 길 때 100개의 문자만 찍힙니다.
- RequestCachingFilter의 이름이 기능을 잘 설명해주지 못하여 RequestLoggingFilter로 이름을 변경하였습니다.
- 
closes #88
=> 88 RequestCachingFilter 로직 변경 

src/main/java/goorm/eagle7/stelligence/domain/document/DocumentController.java
- DocumentController의 swagger의 성공 ResponseExample에서 ResponseTemplate의 results만 보여주던 문제가 있었습니다.
- 이제는 ResponseTemplate 전체를 보여줄 수 있도록 수정하였습니다.
- X
closes #
=> [#91] docs: DocumentController의 swagger에서 ResponseTemplate 전체를 보여줄 수 있도록 수정

build.gradle, src/main/resources/application-local.properties
- 백엔드 모니터링 툴 적용을 위해 build.gradle에 의존성을 추가했습니다.
- 스프링 액츄에이터 (마이크로미터 내장)
- 마이크로미터 프로메테우스 구현체
- 백엔드 모니터링 툴 적용을 위해 application-local.properties에 내용을 추가했습니다.
- 8082 포트를 모니터링을 위한 포트로 설정
- health, prometheus, loggers에 대한 정보를 확인할 수 있도록 엔드포인트 노출
- health는 각 컴포넌트의 상태를 알 수 있도록 설정
- 톰캣의 스레드 정보 등을 알 수 있도록 설정
- X
closes #
=> 95 백엔드 모니터링 관련 설정

src/main/java/goorm/eagle7/stelligence/api/DatabaseConnectionApplicationRunner.java
- 분석기를 바꾸었고 이제 3글자 이상에서도 잘 검색되는 것을 확인했습니다.
- 이미 neo4j 운영환경에도 적용되어 있어 천천히 머지/배포해도 됩니다.
closes #
=> [#104] chore: fulltext index의 분석기를 기본 분석기로 변경

build.gradle, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentServiceReadUnitTest.java
- 테스트 품질 관리를 위한 JaCoCo 라이브러리를 도입했습니다.
- 테스트를 수행하면 build/reports/test/html 하위에 index.html이 생기는데, 이 파일을 열어 테스트 정보를 확인할 수 있습니다.
closes #126
=> 126 JaCoCo 도입

src/test/java/goorm/eagle7/stelligence/domain/member/MemberServiceTest.java
- MemberService test 생성했습니다.
- PR Merge를 기다리며... test를.... 만들었습니다.....
closes #129
---
- 범석님 구두 Review
- given: service 로직 내에서 검증 시에 필요한 행동만 mocking
- then: 자세한 service 로직(구현 내용)이 변경되어도 수행해야 할 일 검증
- when (해당 메서드 수행) 이후 verify, assertThat 등 검증해야 함.
- 이 과정에서 상세 구현 로직까지 검증(verity, assertThat)하지 않음.
- repository를 mocking 시 repository의 일만 mocking(service 로직에서 실행되어야 하는 일과 분리)
- 검증해야 하는 핵심 로직이 아닌 메서드 등을 의존하지 않도록 주의
- test 내에서 string.format, from 등을 사용하게 되면 해당 메서드에 의존하게 되기 때문에 예상하는 값을 하드 코딩으로 비교.
- TODO: 반환 DTO의 from 등에 의존하는 방식 개선, verify 등의 적절성 확인 필요.
=> [#129] test: MemberService test 생성

src/main/java/goorm/eagle7/stelligence/domain/debate/DebateController.java, src/main/java/goorm/eagle7/stelligence/domain/debate/DebateRepository.java, src/main/java/goorm/eagle7/stelligence/domain/debate/DebateService.java, src/main/java/goorm/eagle7/stelligence/domain/debate/dto/DebatePageResponse.java, src/main/java/goorm/eagle7/stelligence/domain/debate/dto/DebateResponse.java, src/main/java/goorm/eagle7/stelligence/domain/debate/dto/DebateSimpleResponse.java, src/main/java/goorm/eagle7/stelligence/domain/debate/model/Debate.java, src/main/java/goorm/eagle7/stelligence/domain/member/dto/MemberSimpleResponse.java, src/test/java/goorm/eagle7/stelligence/config/mockdata/TestFixtureGenerator.java, src/test/java/goorm/eagle7/stelligence/domain/debate/DebateServiceTest.java
- 토론 서비스 로직을 개발하였습니다.
- 수정요청을 토론으로 전환할 수 있습니다.
- 토론을 닫을 수 있습니다.
- 토론을 단건 조회할 수 있습니다.
- 토론 리스트를 페이징을 적용하여 조회할 수 있습니다.
- 토론으로 전환하는 로직과 토론을 종료하는 로직은 추후에 서비스 계층이 아닌 스케쥴러에서 직접 수행하는 것으로 이동될 수 있습니다.
- [@Sooamazing] MemberSimpleResponse에서 Member를 받는 정적 팩토리 메서드를 만들었습니다.
- 토론 테스트의 `void closeOpenDebateById()`에서 토론이 종료되었을때 `endAt`이 정상적으로 업데이트 되었는지를 아래와 같이 업데이트된 `endAt`이 현재 시간과 10초 이상 차이나지 않는지를 확인하고 있습니다. 더 괜찮은 방식이 있다면 피드백 부탁드립니다.
- `assertThat(debate.getEndAt()).isCloseTo(LocalDateTime.now(), within(10, ChronoUnit.SECONDS));`
closes #
=> 127 토론 서비스 로직 개발

src/main/java/goorm/eagle7/stelligence/domain/contribute/scheduler/MergeHandler.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/MergeHandlerTest.java
- MergeHandler의 파라미터가 Contribute 타입에서 Long contributeId로 바뀌면서 메서드 시그니처를 통해 캐시를 무효화 할 수 있는 방법이 제한되었던 문제가 있었습니다. (기존에는 #contribute.document.id 를 통해 캐시 무효화)
- 이를 해결하기 위해 CacheManager를 의존주입 받아 직접 evict를 수행하게 만들었습니다.
closes #138
=> 138 feat: 문서 내용 조회시 캐싱 적용

build.gradle, src/main/java/goorm/eagle7/stelligence/common/image/ImageUploadController.java, src/main/java/goorm/eagle7/stelligence/config/S3Config.java
- /api/images/upload를 통해 사용자는 이미지 바이너리 데이터를 서버로 전송하고, 해당 이미지를 볼 수 있는 url을 응답으로 확인할 수 있습니다.
- 5MB 이하의 파일만 받을 수 있으며, 이는 컨트롤러의 정적 변수를 통해 변경 가능합니다.
-  IMG 형식만 받습니다.
- aws.properties를 추가하여야 정상적으로 동작합니다. 이 내용은 슬랙을 통해 전달하겠습니다.
@eenzzi  @youngandmini  @Sooamazing 
closes #153
=> 153 Image Controller 구현

src/main/java/goorm/eagle7/stelligence/domain/debate/dto/DebateResponse.java
- DebateResponse의 필드에 토론 종료 여부를 추가하였습니다.
- 없습니다
closes #
=> [#169] refactor: DebateResponse에 토론 종료 여부 추가

src/main/java/goorm/eagle7/stelligence/common/login/CookieUtils.java
- domain, sameSite, secure 설정 제거
- 이걸 한다고 되는지는 모르겠으나 현재 프론트 페이지에서 소셜 로그인 버튼 세 개는 {server}:8080/oauth2 ~~~ 로 연결, 다른 건 다 {server}/api/어쩌구~~ 이거인데, server 주소에서 요청 보내는 건 헤더 Set-Cookie 설정은 되지만, 쿠키가 안 오는 상황
- 메인과 로그인스페샬과 설정이 다른 건 해당 3개 설정이라 우선 제거 후 상황 파악 예정.
- 안 되면... 되게 하라....
closes #141
=> [#141] bug: Set-Cookie는 보이나 쿠키가 가지 않는 문제 생겨 수정.

src/main/java/goorm/eagle7/stelligence/domain/debate/repository/DebateRepository.java, src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/dto/DocumentResponse.java, src/main/java/goorm/eagle7/stelligence/domain/section/model/Section.java, src/test/java/goorm/eagle7/stelligence/domain/debate/repository/DebateRepositoryTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentServiceReadUnitTest.java
- 이제는 DocumentResponse에 최종수정일시 가 포함됩니다.
- 이제는 DocumentResponse에 '수정 가능 여부' 가 포함됩니다.
- 수정 가능 여부는 토론이 진행중인지와 투표가 진행중인지에 대한 여부로, 둘다 진행중이 아닌경우에만 true로 표현됩니다.
- DocumentResposne의 유저 표현이 MemberDetailResposne에서 MemberSimpleResposne로 바뀌었습니다.
- Section.content의 데이터타입이 TEXT로 바뀌었습니다.
- @youngandmini DebateRepository에 메서드 추가하고 테스트코드 작성했습니다.
closes #171
=> 171 Document Content 반환 타입 대대적인 수정

src/main/java/goorm/eagle7/stelligence/config/HtmlPolicyConfig.java, src/test/java/goorm/eagle7/stelligence/config/HtmlPolicyConfigTest.java
- 이제 img 태그가 글에 포함될 수 있습니다.
- 
closes #181
=> 181 HTML Sanitizer img 태그 허용

src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeRequestValidator.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeService.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/dto/ContributeRequest.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/dto/ContributeResponse.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/model/Contribute.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/scheduler/MergeHandler.java, src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/model/Document.java, src/main/java/goorm/eagle7/stelligence/domain/document/graph/DocumentGraphService.java, src/test/java/goorm/eagle7/stelligence/config/mockdata/TestFixtureGenerator.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/ContributeRequestValidatorTest.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/ContributeSchedulingActionDeterminerTest.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/DebateHandlerTest.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/MergeHandlerTest.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/RejectHandlerTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/DocumentServiceTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentServiceCreateUnitTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentServiceTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/graph/DocumentGraphServiceTest.java
- 요구사항 변경에 따라 Document 엔티티에서 상위 문서를 참조하도록 변경되었습니다.
- @eenzzi 수정 요청사항에 대해서 보다 적절한 응답을 하도록 ContributeResponse를 수정하였습니다
- 수정요청이 병합될 때, 문서컨텐츠와 문서그래프 모두에서 제목과 상위문서 변경이 반영되도록 하였습니다.
- Contribute / Document / DocumentGraph 등 많은 도메인에 걸친 부분이 수정되었습니다.
- 열심히 체크했지만, 부족한 부분이 많을 것 같습니다.
- 꼼꼼하게 체크해서 빠진 부분 말씀 부탁드립니다.
closes #
=> 191 document entity saves parentdocument

src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeRepository.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeRequestValidator.java, src/main/java/goorm/eagle7/stelligence/domain/document/DocumentRequestValidator.java, src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentRepository.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/ContributeRepositoryTest.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/ContributeRequestValidatorTest.java, src/test/java/goorm/eagle7/stelligence/domain/debate/repository/DebateRepositoryTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/DocumentRequestValidatorTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/DocumentServiceTest.java, src/test/resources/dummy.sql
- 이제는 애플리케이션 단에서 문서의 제목이 중복되는 것을 막습니다.
- 다음과 같은 검증 메서드가 추가되었습니다.
-  이미 해당 제목을 가진 문서가 존재하는가
-  수정요청에서 해당 제목으로 변경하고자 하는 요청이 존재하는가
- 수정요청을 등록하는 시점에서 ContributeRequestValidator는 위 두 내용을 검증합니다.
- 글을 생성하는 시점에서 DocumentRequestValidator는 위 두 내용을 검증합니다.
- 테스트코드 반영하였습니다.
- 
closes #202
=> 202 중복된 제목 등록 및 변경 막기

src/main/java/goorm/eagle7/stelligence/config/SwaggerConfig.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeRequestValidator.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentRepository.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/ContributeRequestValidatorTest.java
- Contribute 생성 시 변경하고자하는 문서의 제목을 바꾸지 않았을 때, exist의 결과를 문서 제목의 중복이라고 판단하여 에러를 발생시키던 문제를 해결
- 
closes #202
=> 202-문서-제목-중복-해결

src/main/java/goorm/eagle7/stelligence/domain/contribute/custom/CustomContributeRepository.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/custom/CustomContributeRepositoryImpl.java, src/main/java/goorm/eagle7/stelligence/domain/debate/model/Debate.java, src/main/java/goorm/eagle7/stelligence/domain/debate/repository/CustomDebateRepository.java, src/main/java/goorm/eagle7/stelligence/domain/debate/repository/CustomDebateRepositoryImpl.java, src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/dto/DocumentResponse.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/dto/DocumentStatus.java, src/test/java/goorm/eagle7/stelligence/domain/debate/DebateServiceCommentTest.java, src/test/java/goorm/eagle7/stelligence/domain/debate/model/DebateTest.java, src/test/java/goorm/eagle7/stelligence/domain/debate/repository/DebateRepositoryTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentServiceReadUnitTest.java, src/test/resources/dummy.sql
- 문서 상세 조회 시 다음과 같은 필드를 함께 확인할 수 있습니다.
- 문서 상태: 수정가능 / 투표중 / 토론중 / 토론후수정대기중
- 상위 문서 조회
- X
closes #
=> 216 문서 상세 조회 시 상위문서태그와 투표중 토론중 토론수정대기중 상태 반환

src/main/java/goorm/eagle7/stelligence/domain/member/dto/MemberBadgesResponse.java
- badgeResponse에서 imgUrl, description 순서 뒤바뀌어서 정정
- 
closes #236
=> [#236] fix: badgeResponse imgUrl, description 순서 잘못돼 정정

src/main/java/goorm/eagle7/stelligence/domain/debate/DebateService.java, src/main/java/goorm/eagle7/stelligence/domain/debate/model/Comment.java, src/test/java/goorm/eagle7/stelligence/domain/debate/DebateServiceCommentTest.java
- 비즈니스 요구사항에 따라 토론 댓글의 글자수를 1000자로 제한하는 로직을 추가하였습니다.
- 아래 링크를 참고하여, 최대 길이가 (상대적으로) 크지 않으므로 TEXT가 아닌 VARCHAR(1000)으로 결정하였습니다.
- https://medium.com/daangn/varchar-vs-text-230a718a22a1
closes #
=> 233 토론 댓글 글자수 제한 1000자로 조정

src/main/java/goorm/eagle7/stelligence/common/auth/filter/AuthFilter.java, src/main/java/goorm/eagle7/stelligence/common/auth/filter/PermittedPathStore.java
- /api/login 에서 CORS error 지속 발생해 디버깅 중 postman에서 options로 보내면 authfilter에서 uri pass가 아닌 것 확인해 추가
- 기존 테스트 시 headers - origin, www.stelligence.site는 통과했음.
- Access to XMLHttpRequest at 'https://api.stelligence.site/api/login' from origin 'http://www.stelligence.site' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
- cors 해결해야 프론트 다른 테스트 가능해 긴급 병합 시도.
closes #
=> [#250] fix: preflight 해결 위해 POST uri에 OPTIONS 추가

src/main/java/goorm/eagle7/stelligence/common/auth/filter/AuthFilter.java
- authFilter에서 Options 메서드면 무조건 200 OK 반환하는 코드 추가
- 임시 방편으로 우선, 200 반환하면 되는지 확인 위함.
- 
closes #252
=> [#252] fix: preflight 해결 위해 OPTIONS면 바로 200 반환하는 코드 추가 - 임시방편

src/main/java/goorm/eagle7/stelligence/domain/document/content/parser/TagDocumentParser.java, src/main/java/goorm/eagle7/stelligence/domain/section/model/Heading.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/template/CreateAmendmentMergeTemplateTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/parser/TagDocumentParserTest.java
- 이제는 헤딩 태그를 3까지로 제한해서 관리합니다.
- h4에서 h6이 오는 경우는 오류로 처리하지 않고, h3으로 변경하여 저장합니다.
- 
closes #261
=> 261 헤딩 태그 1~3으로 제한

src/main/java/goorm/eagle7/stelligence/common/auth/filter/pathmatch/PermittedPathStore.java, src/main/java/goorm/eagle7/stelligence/common/auth/memberinfo/MemberInfoArgumentResolver.java, src/main/java/goorm/eagle7/stelligence/domain/bookmark/BookmarkController.java, src/main/java/goorm/eagle7/stelligence/domain/bookmark/BookmarkService.java, src/main/java/goorm/eagle7/stelligence/domain/bookmark/dto/BookmarkOneResponse.java, src/main/java/goorm/eagle7/stelligence/domain/member/MemberRepository.java
- 북마크 단건 조회 api 생성
- /api/bookmarks/marked
- 요구사항: 로그인하지 않은 사용자가 볼 때는 400 ex -> AuthFilter 로직 변경 필요해 추후 보강 예정.
closes #278
=> 278 bookmark one get api

src/main/java/goorm/eagle7/stelligence/domain/document/DocumentRequestValidator.java, src/main/java/goorm/eagle7/stelligence/domain/notification/NotificationRepository.java, src/main/java/goorm/eagle7/stelligence/domain/notification/NotificationService.java, src/main/java/goorm/eagle7/stelligence/domain/notification/custom/CustomNotificationRepositoryImpl.java, src/main/java/goorm/eagle7/stelligence/domain/notification/model/Notification.java, src/test/java/goorm/eagle7/stelligence/domain/document/DocumentRequestValidatorTest.java, src/test/java/goorm/eagle7/stelligence/domain/notification/NotificationRepositoryTest.java
- 이제는 Notification이 Member를 가지고 있지 않습니다.
- DB 레벨에서도 FK를 갖고 있지 않습니다.
- 따라서 쿼리 실패의 가능성도 줄어드므로, customNotificationRepository에서 예외처리관련 코드부분을 제거했습니다.
- 
closes #267
=> 267 Notification과 Member의 연관관계 및 FK 제거

src/main/java/goorm/eagle7/stelligence/domain/document/DocumentController.java
- Document Graph 탐색 시, root / depth 파라미터가 더 이상 필요 없어 삭제하였습니다.
- 
closes #
=> [#275] refactor: Document Graph 탐색 시, root / depth 파라미터 삭제

src/main/java/goorm/eagle7/stelligence/common/auth/filter/AuthFilter.java, src/main/java/goorm/eagle7/stelligence/common/auth/filter/pathmatch/CustomRequestMatcher.java, src/main/java/goorm/eagle7/stelligence/common/auth/filter/pathmatch/PermittedPathStore.java, src/main/java/goorm/eagle7/stelligence/common/auth/filter/pathmatch/ResourceAntPathMatcher.java, src/main/java/goorm/eagle7/stelligence/common/auth/memberinfo/MemberInfoArgumentResolver.java, src/main/java/goorm/eagle7/stelligence/common/auth/oauth/handler/OAuth2LogoutCustomHandler.java, src/test/java/goorm/eagle7/stelligence/common/auth/filter/pathmatch/PermittedPathStoreTest.java
- permitAll인 uri에서는 Authentication을 저장하는 어떤 로직도 수행하지 않아서 @Auth 바인딩 시 아예 500 에러가 나고, null이 받아와지지 않아서, @Auth를 사용하는 uri라면 null / MemberInfo 둘 중 하나를 받게 하려 함.
- 바꿔야 하는 이유
- 기존 권한 필요 없는 url (security의 permitAll 이용) : get, /api/documents/**, /api/contributes/**, /api/comments/**, /api/debates/**
- 권한 필요 없는 url에서는 @Auth 이용하지 않는다 가정
- get, /api/contributes/**/votes 에서도 @Auth 사용, 이 경우 token 검증하는 로직을 아예 거치지 않아 @Auth 매핑하지 않음. 
- 해당 로직 변경 
- -> 기존: 권한 필요한 uri에서 토큰 검증 후 검증 실패 시 logout uri 제외하고 401 
- -> 변경 내용: 권한 필요 없는 uri 중 @Auth 필요한 곳 제외, 해당 uri를 검증, 검증 실패한 uri 중 MEMBERINFO_REQUIRED_RESOURCES에 있던 uri라면 임의의 userId를 넣어준 후, Resolver에서 해당 userId인 경우 null 반환
- pathStore에서 pathSet 따로 관리
- get votes, get bookmark/marked , logout 함께 설정
- 추후 security anonymous 적절하면 적용 예정.
- 권한 있어야 하는 곳 중 권한 없이도 볼 수 있는 곳에 대한 …
=> 269 auth에서 memberinfo 받아지지 않음 -> 로그인 권한 로직 재구성

src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeRequestValidator.java, src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeService.java, src/test/java/goorm/eagle7/stelligence/domain/contribute/ContributeRequestValidatorTest.java
- 아래와 같은 조건에 따라 검증을 수행하도록 ContributeRequestValidator를 수정하였습니다.
1. 토론이 진행중인가? - 수정요청 불가
1. 토론이 종료된 후 토론 참여자를 위한 수정요청 대기중인가?
1. 다른 토론에서 파생된 수정요청을 보내는 경우 - 수정요청 불가
1. 토론 참여자가 아닌 사람이 수정요청을 보내는 경우 - 수정요청 불가
- 메서드 이름이 생각이 잘 안나서 checkDebate로 하였습니다..
- 더 좋은 이름이 있다면 추천 부탁드립니다!!
closes #
=> [#232] feat: 수정요청 대기중인 문서에 대한 검증 로직 추가

src/main/java/goorm/eagle7/stelligence/api/GlobalRestControllerAdvice.java
- PathVariable이 잘못되었을때 서버에러로 인식되는 버그를 수정하였습니다.
- GlobalRestControllerAdvice에 MethodArgumentTypeMismatchException를 처리하는 ExceptionHandler를 추가하였습니다.
- 
closes #
=> [#312] fix: PathVariable이 잘못되었을때 서버에러로 인식되는 버그 수정

src/main/java/goorm/eagle7/stelligence/domain/document/graph/DocumentNodeRepository.java, src/test/java/goorm/eagle7/stelligence/domain/document/graph/DocumentNodeRepositoryTest.java
- 제목으로 검색시에 spring을 검색하면 Spring이 나오지 않는 식으로 대소문자가 구분되는 문제가 있었습니다.
- 이제는 대소문자 구분 안하고 검색을 수행할 수 있습니다.
- 
closes #
=> [#322] fix: 제목으로 문서 검색시 대소문자 구분 안하도록 수정

src/main/java/goorm/eagle7/stelligence/domain/amendment/AmendmentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/parser/TagDocumentParser.java, src/test/java/goorm/eagle7/stelligence/config/HtmlPolicyConfigTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentServiceCreateUnitTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/parser/TagDocumentParserTest.java
- 이제는 수정요청으로 들어오는 html 문자열도 sanitize의 대상이 됩니다.
- 기존에 DocumentParser에서 수행되던 sanitize를 제거하였고, sanitize의 책임을 documentContentService와 amendmentService에 부여하였습니다.
- 
closes #318
=> 318 amendment html sanitize

src/main/java/goorm/eagle7/stelligence/domain/document/DocumentController.java, src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/dto/DocumentSimpleResponse.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentServiceReadUnitTest.java
- 기존에는 제목 검색이 해당 문자열을 포함하는 문서를 검색하는 방식이었습니다.
- 언급링크를 위해 정확히 입력한 제목과 일치하는 문서를 검색하는 API를 추가하였습니다.
- X
closes #
=> 328 언급링크를 위한 제목검색 완전일치 api 추가

src/test/java/goorm/eagle7/stelligence/domain/badge/BadgeServiceTest.java
- 발급 성공, 카테고리가 없는 경우, 만족하는 배지가 없는 경우로 나눠 테스트 작성.
- notificationTest가 뜬금없이.. 깨지고, 다시 하니 통과....! @sbslc2000 
- 그냥 제 컴퓨터 이상인가 싶어서 우선 에러났던 로그 첨부합니다,,
```
java.lang.AssertionError: 
Expected size: 3 but was: 10 in:
[goorm.eagle7.stelligence.domain.notification.model.Notification@70e7914e,
goorm.eagle7.stelligence.domain.notification.model.Notification@66b00ffe,
goorm.eagle7.stelligence.domain.notification.model.Notification@4d5fd888,
goorm.eagle7.stelligence.domain.notification.model.Notification@20b8e765,
goorm.eagle7.stelligence.domain.notification.model.Notification@d2fc6e1,
goorm.eagle7.stelligence.domain.notification.model.Notification@4da61cd5,
goorm.eagle7.stelligence.domain.notification.model.Notification@221cf6e2,
goorm.eagle7.stelligence.domain.notification.model.Notification@67ced751 …
```
=> 326 badge service test 작성

src/main/java/goorm/eagle7/stelligence/domain/document/DocumentRequestValidator.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java, src/main/java/goorm/eagle7/stelligence/domain/document/content/SectionRequestValidator.java, src/test/java/goorm/eagle7/stelligence/domain/document/SectionRequestValidatorTest.java, src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentServiceCreateUnitTest.java
- 이제는 파싱된 섹션 정보에 대한 길이 유효성 검증을 수행합니다.
- 
closes #349
=> 349 sectionrequest validation
