- src/main/java/goorm/eagle7/stelligence/common/entity/BaseTimeEntity.java
- src/main/java/goorm/eagle7/stelligence/config/JpaAuditingConfig.java
- src/test/java/goorm/eagle7/stelligence/common/entity/BaseTimeEntityTest.java
- JpaAuditing 기능을 사용하여 생성시간과 수정시간을 자동으로 변경해주는 상위 클래스를 개발했습니다.
> [#7] BaseTimeEntity 생성 및 테스트코드 작성

- src/main/java/goorm/eagle7/stelligence/domain/commit/CommitRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/commit/model/Commit.java
- src/main/java/goorm/eagle7/stelligence/domain/commit/model/CommitStatus.java
- src/main/java/goorm/eagle7/stelligence/domain/commit/model/CommitType.java
- src/main/java/goorm/eagle7/stelligence/domain/commit/model/NewSectionHeading.java
- 수정안 entity 생성
- 수정안 repository 생성
- 없습니다!
> 6 수정안 entity 생성

- src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java
- src/main/java/goorm/eagle7/stelligence/domain/document/parser/DocumentParser.java
- src/test/java/goorm/eagle7/stelligence/domain/document/DocumentMergeConcurrencyTest.java
- src/test/java/goorm/eagle7/stelligence/domain/document/DocumentServiceSpringBootTest.java
- src/test/java/goorm/eagle7/stelligence/domain/document/parser/DocumentParserTest.java
- 클라이언트측에서 제공되는 글은 섹션 정보 없이 마크다운으로만 들어오기 때문에, 이를 해석하여 섹션구조로 만드는 파싱 모듈을 개발하였습니다.
- 관련 테스트코드를 변경했습니다.
- 없습니당
closes #18
> 18 글 파싱 모듈 개발

- src/main/java/goorm/eagle7/stelligence/common/sequence/SequenceTableInitiator.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/model/Contribute.java
- src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java
- src/main/java/goorm/eagle7/stelligence/domain/document/dto/DocumentResponse.java
- src/test/java/goorm/eagle7/stelligence/common/merge/MergeServiceIntegratedTest.java
- src/test/java/goorm/eagle7/stelligence/config/DummyInsertManager.java
- src/test/java/goorm/eagle7/stelligence/config/MockSectionIdGenerator.java
- src/test/java/goorm/eagle7/stelligence/config/TestConfig.java
- src/test/java/goorm/eagle7/stelligence/config/mockdata/MockDataConfig.java
- src/test/java/goorm/eagle7/stelligence/config/mockdata/TestFixtureGenerator.java
- src/test/java/goorm/eagle7/stelligence/config/mockdata/WithMockData.java
- src/test/java/goorm/eagle7/stelligence/domain/document/DocumentMergeConcurrencyTest.java
- src/test/java/goorm/eagle7/stelligence/domain/document/DocumentServiceCreateTest.java
- src/test/java/goorm/eagle7/stelligence/domain/document/DocumentServiceReadTest.java
- src/test/java/goorm/eagle7/stelligence/domain/document/DocumentServiceSpringBootTest.java
- src/test/java/goorm/eagle7/stelligence/domain/section/SectionRepositoryTest.java
- src/test/resources/dummy.sql
- dummy.sql 추가 : 테스트용으로 사용할 insert 문을 담았습니다.
- @WithMockData 애노테이션을 통해 스프링부트 테스트시 더미데이터를 사용할 수 있습니다.
- TestFixtures를 통해 단위테스트시 비교적 편하게 엔티티 객체를 생성할 수 있습니다.
- 무
closes #21
> 21 테스트 환경 구축

- src/main/java/goorm/eagle7/stelligence/api/GlobalRestControllerAdvice.java
- src/main/java/goorm/eagle7/stelligence/api/ResponseTemplate.java
- src/main/java/goorm/eagle7/stelligence/domain/document/DocumentController.java
- src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java
- src/main/java/goorm/eagle7/stelligence/domain/document/dto/DocumentCreateRequest.java
- src/main/resources/application-local.properties
- DocumentController 개발
- 생성 API
- 단건 글 내용 조회 API
- 없을 무
closes #30
> 30 문서 생성 및 조회 api 개발

- src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java
- src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentRepositoryTest.java
- src/test/resources/dummy.sql
- 문서의 내용을 기반으로 검색하여 문서의 ID를 가져오는 서비스 코드를 작성했습니다.
- 없습니다.
closes #32
> 32 문서 내용 검색 기능 개발

- src/main/java/goorm/eagle7/stelligence/common/merge/MergeService.java
- src/main/java/goorm/eagle7/stelligence/config/RedisConfig.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java
- src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentServiceCachingTest.java
- 게시글 캐싱의 대상을 최신 글로 한정하였습니다.
- 
closes #
> 39 캐싱 기능 최신 글에만 적용

- src/main/java/goorm/eagle7/stelligence/domain/document/graph/DocumentGraphService.java
- src/main/java/goorm/eagle7/stelligence/domain/document/graph/DocumentNodeRepository.java
- src/test/java/goorm/eagle7/stelligence/domain/document/graph/DocumentGraphServiceTest.java
- 처음 조회 시에는 루트 노드를 기준으로 조회할 수 있어야합니다.
- 이에 따라 관련 기능을 개발하였습니다.
- X
closes #
> 42 그래프 뷰 조회 시 초기 최상위 노드 검색 기능 구현

- src/main/java/goorm/eagle7/stelligence/domain/document/content/parser/DocumentParser.java
- src/test/java/goorm/eagle7/stelligence/domain/document/content/parser/DocumentParserTest.java
- 이제는 글 생성 시 제목에 띄어쓰기를 넣어도 됩니다.
- 
closes #52
> [#52] bug: 제목에 띄어쓰기가 있는 경우의 문제 해결

- src/main/java/goorm/eagle7/stelligence/config/SwaggerConfig.java
- src/main/java/goorm/eagle7/stelligence/domain/document/DocumentController.java
- Swagger API Docs에 접근할 때 뜨는 헤더 문구를 수정했습니다.
- 
closes #58
> 58 swagger 설정 추가

- src/main/java/goorm/eagle7/stelligence/common/merge/MergeService.java
- src/main/java/goorm/eagle7/stelligence/common/merge/template/AmendmentMergeTemplate.java
- src/main/java/goorm/eagle7/stelligence/common/merge/template/AmendmentMergeTemplateMapper.java
- src/main/java/goorm/eagle7/stelligence/common/merge/template/CreateAmendmentMergeTemplate.java
- src/main/java/goorm/eagle7/stelligence/common/merge/template/DeleteAmendmentMergeTemplate.java
- src/main/java/goorm/eagle7/stelligence/common/merge/template/UpdateAmendmentMergeTemplate.java
- src/main/java/goorm/eagle7/stelligence/common/sequence/JdbcSectionIdGenerator.java
- src/main/java/goorm/eagle7/stelligence/common/sequence/SequenceTable.java
- src/main/java/goorm/eagle7/stelligence/common/sequence/SequenceTableInitiator.java
- src/main/java/goorm/eagle7/stelligence/domain/document/DocumentController.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentCacheAspect.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/dto/DocumentResponse.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/dto/SectionRequest.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/model/Document.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/parser/DocumentParser.java
- Document 관련 파트의 미비했던 로깅과 주석들을 보강했습니다.
- 
closes #62
> 62 document logging

- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeController.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeService.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/custom/CustomContributeRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/custom/CustomContributeRepositoryImpl.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/dto/ContributeRequest.java
- contribute controller 생성
- 
closes #
> [#93] feat: 수정요청 controller 생성

- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeController.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeService.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/dto/ContributeListResponse.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/dto/ContributeRequest.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/dto/ContributeResponse.java
- 목록 조회용 dto를 만들었습니다
- 
closes #
> 107 수정요청 목록 조회 dto 생성

- src/main/java/goorm/eagle7/stelligence/domain/contribute/scheduler/ContributeSchedulingAction.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/scheduler/ContributeSchedulingActionDeterminer.java
- src/main/java/goorm/eagle7/stelligence/domain/vote/DummyVoteRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/vote/VoteCustomRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/vote/VoteSummary.java
- src/test/java/goorm/eagle7/stelligence/config/mockdata/TestFixtureGenerator.java
- src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/ContributeSchedulingActionDeterminerTest.java
- src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/template/CreateAmendmentMergeTemplateTest.java
- src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/template/DeleteAmendmentMergeTemplateTest.java
- src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/template/UpdateAmendmentMergeTemplateTest.java
- Contribute의 배치 작업에서 수행해야할 로직을 판단하는 모듈을 만들었습니다.
-  Vote 관련 코드 : 특정 Contribute의 투표 현황을 가져올 수 있는 인터페이스 (추후 @eenzzi 님 개발 예정)
- Action Enum : 수행해야할 로직 목록
- ActionDeterminer : 투표 결과를 기반으로 수행해야할 로직을 결정
- 테스트 코드 작성했습니다.
-  AmendmentTemplate 관련 테스트 코드도 함께 넣었습니당 ㅎㅎ ㅠㅠ 원래 따로 해야하는게 맞지만 이번만 부탁드립니당. 이번에 깃을 잘못 운용해서.. 빠르게 로컬에 반영안된 파일들 쳐내야할것 같아서 그랬습니당
closes #103
> 103 contribute-scheduling-action

- src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/dto/DocumentResponse.java
- src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentRepositoryTest.java
- src/test/resources/dummy.sql
- 이제는 개별 문서 조회에서 기여자 정보를 확인할 수 있습니다.
- 
closes #117
> 117 문서 기여자 조회

- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeRequestValidator.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeService.java
- src/main/java/goorm/eagle7/stelligence/domain/section/SectionRepository.java
- src/test/java/goorm/eagle7/stelligence/domain/contribute/ContributeRequestValidatorTest.java
- Contribute와 Amendment는 정해진 규칙 내에서 들어와야 글을 수정하는데에 문제가 발생하지 않습니다.
- 이 검증은 내용이 많고 복잡하기 때문에 별도의 클래스에서 수행할 수 있도록 만들었습니다.
- 이제는 규칙에 따르지 않은 ContributeRequest가 들어오는 경우 Exception을 발생시킵니다.
- ContributeService에 코드 한 줄을 추가했습니다. @eenzzi 
closes #130
> 130 ContributeRequestValidator 개발 및 적용

- src/main/java/goorm/eagle7/stelligence/common/auth/filter/DevAuthFilter.java
- src/main/java/goorm/eagle7/stelligence/common/auth/filter/RequestResource.java
- src/main/java/goorm/eagle7/stelligence/common/auth/filter/ResourceAntPathMatcher.java
- src/main/java/goorm/eagle7/stelligence/common/auth/filter/ResourceMemoryRepository.java
- login 필요하지 않은 uri 추가, 필요한 곳에서만 자동 로그인 및 회원 가입 진행
- 오만 군데에서 회원 가입하는 것은 정말 ... 불필요합니다...
closes #154
> 154 any login stop login

- src/main/java/goorm/eagle7/stelligence/domain/member/model/Member.java
- src/test/resources/dummy.sql
- amendment는 여전히 깨짐..
- 
- amendmentServiceTest 3개 깨짐 -> 범석님이 고쳐주기로 함.
closes #184
> [#184] bug: member bookmark 변경 alc deleted 추가로 dummy.sql, member 변경

- src/test/java/goorm/eagle7/stelligence/domain/contribute/scheduler/ContributeSchedulingActionDeterminerTest.java
- ContributeActionDeterminer에서 투표가 없는 경우 reject가 발생해야한다는 요구사항의 테스트코드를 작성했습니다.
- 
closes #185
> 185 contributeactiondeterminer new testcase

- src/main/java/goorm/eagle7/stelligence/common/login/CookieUtils.java
- src/main/java/goorm/eagle7/stelligence/config/WebConfig.java
- cookie 다양한 조작 위해 설정 켜둠.
- 
closes #195
> 195    cors cookie plz

- src/main/java/goorm/eagle7/stelligence/common/auth/filter/DevAuthFilter.java
- src/main/java/goorm/eagle7/stelligence/config/WebConfig.java
- exposedHeaders 추가하려 했으나 필요 없을 것 같아 devauthfilter에 log만 추가
- 쿠키는.. 이제 .... application에서는 보이는데, 프론트에서 여전히 로그인 정보가 계속 바뀌어 쿠키가 서버로 오느느 게 맞는지 확인 필요.
closes #197
> 197   auth   exposedheaders plz

- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeController.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeService.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/custom/CustomContributeRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/custom/CustomContributeRepositoryImpl.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/dto/ContributePageResponse.java
- 목록 조회를 투표중, 투표 완료(전체/상태에 따라), 문서에 따른 반영 완료/미반영 으로 나눠서 추가했습니다.
- page 속성을 필요한 것만 반환되도록 ContributePageResponse를 추가했습니다.
- 뭔가... 굉자히... 지저분한데.. 이게 맞나.......
- 쿼리 한 요청에 20번넘게 나가는데....맞나......
closes #
> 193 contribute 목록 조회 변경

- src/main/java/goorm/eagle7/stelligence/domain/notification/NotificationController.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/NotificationRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/NotificationRequest.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/NotificationSender.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/NotificationService.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/dto/response/NotificationResponse.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/model/Notification.java
- Notification을 읽음처리하고 삭제하는 기능을 추가하였습니다.
- Notification을 보낼 수 있는 통로 역할을 할 NotificationSender를 만들었습니다.
- Notification을 전송하려면 NotificationRequest 객체를 만들어 전송해주어야 합니다.
- 테스트코드는 별도의 PR에서 작성하겠습니다.
closes #152
> 152 notification 조회 및 읽음 처리와 삭제 

- src/main/java/goorm/eagle7/stelligence/config/WebConfig.java
- cors 설정 수정.
- 수정
closes #208
> 208  front domain cors

- src/main/java/goorm/eagle7/stelligence/domain/document/DocumentService.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentService.java
- src/main/java/goorm/eagle7/stelligence/domain/document/content/dto/DocumentResponse.java
- src/test/java/goorm/eagle7/stelligence/domain/document/content/DocumentContentServiceReadUnitTest.java
- 이제 개별 글 조회에서는 currentRevision과 latestRevision을 제공합니다.
- currentRevision: 조회 요청의 버전
- latestRevision: 문서의 최신 버전 
closes #207
> 207 문서 조회시 현재/최신 버전 제공

- src/main/java/goorm/eagle7/stelligence/domain/debate/dto/DebateResponse.java
- 이전 토론과 다음 토론이 요구사항의 변경에 따라 삭제하였습니다.
- 
closes #
> 224 토론 응답의 이전토론 다음토론 필드 삭제

- src/main/java/goorm/eagle7/stelligence/domain/notification/custom/CustomNotificationRepositoryImpl.java
- notificationSender에서 message로 '' 가 들어오는 경우 쿼리가 정상적으로 생성되지 못하는 문제를 해결했습니다.
- 
closes #212
> [#212] feat: message 내에 '' 가 들어오는 것을 처리하기 위해 파라미터 바인딩 사용

- src/main/java/goorm/eagle7/stelligence/domain/debate/DebateService.java
- src/main/java/goorm/eagle7/stelligence/domain/debate/event/NewCommentEvent.java
- src/main/java/goorm/eagle7/stelligence/domain/debate/repository/CommentRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/listener/debate/NewCommentNotifier.java
- src/test/java/goorm/eagle7/stelligence/domain/debate/DebateServiceCommentTest.java
- src/test/java/goorm/eagle7/stelligence/domain/notification/listener/debate/NewCommentNotifierTest.java
- 새 댓글이 달렸을 때 알림을 보내는 역할을 하는 이벤트 핸들러 클래스를 만들었습니다.
- 
closes #245
> 245 comment notification

- src/main/java/goorm/eagle7/stelligence/domain/bookmark/BookmarkRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/listener/BookmarkedDocumentChangedNotifier.java
- src/test/java/goorm/eagle7/stelligence/domain/notification/listener/BookmarkedDocumentChangedNotifierTest.java
- 북마크한 글이 변경되었을 때 사용자에게 알림을 전송합니다.
- 
closes #248
> 248 bookmark document change notifier

- src/main/java/goorm/eagle7/stelligence/common/auth/filter/AuthFilter.java
- src/main/java/goorm/eagle7/stelligence/common/auth/filter/CorsFilter.java
- src/main/java/goorm/eagle7/stelligence/common/auth/jwt/JwtTokenReissueService.java
- 이전 시도는 처참히 실패, 되던 로그인도 안 됨.
- CorsFilter 제작해 1번으로 추가
- 
closes #254
> 254 corsFilter 제작, 로그 추가.

- src/main/java/goorm/eagle7/stelligence/common/auth/filter/CorsFilter.java
- - set-cookie도 우선 추가
- 하나씩 추가하고 빼다 보니, 실험용이 많아짐...
closes #256
> [#256] fix: header에 빠져서 content-type 추가

- src/main/java/goorm/eagle7/stelligence/domain/contribute/model/Contribute.java
- src/main/java/goorm/eagle7/stelligence/domain/debate/model/Debate.java
- src/main/resources/application-local.properties
- src/test/java/goorm/eagle7/stelligence/domain/debate/DebateServiceCommentTest.java
- 원활한 개발 테스트를 위해 스케쥴링 시간을 조정합니다.
- X
closes #
> 266 scheduling time update

- src/main/java/goorm/eagle7/stelligence/common/auth/filter/pathmatch/PermittedPathStore.java
- src/main/java/goorm/eagle7/stelligence/config/RequestContextListenerConfig.java
- src/main/java/goorm/eagle7/stelligence/config/WebConfig.java
> 265 requestcontextholder error

- src/main/java/goorm/eagle7/stelligence/common/auth/filter/AuthFilter.java
- ! 검증... 실수...
- 우선, 요청 시마다 쿠키 재발급하는 로직 수정.
- 재발급 로직 자체는 로그를 확인했을 때, 정상으로 보여 해당 이슈만 빠르게 변경
- 중복 쿠키가 계속 발생하는지는 추후 확인 필요.
closes #286
> [#286] 중복 쿠키 생성 문제-refresh 토큰 재발급 로직 수정

- src/main/java/goorm/eagle7/stelligence/domain/vote/VoteController.java
- vote api 요청 시 반환되게 수정
- 
closes #
> [#289] refactor: vote 요청시 반환되게 수정

- src/main/java/goorm/eagle7/stelligence/common/auth/filter/AuthFilter.java
- src/main/java/goorm/eagle7/stelligence/common/auth/oauth/handler/OAuth2LogoutCustomHandler.java
- src/main/java/goorm/eagle7/stelligence/common/dev/DevLoginController.java
- src/main/java/goorm/eagle7/stelligence/config/SecurityConfig.java
- logout 시 응답으로 만료된 쿠키는 오지만, 실제 있던 쿠키가 사라지지 않아 logout 처리되지 않는 문제 
- 네트워크 창 분석 시 security에서 자동으로 진행하는 cookie의 설정 문제로 추정
- security에서 cookie 지우기 제외, logoutHandler에서 직접 cookie delete 진행
- 안 되면.. 다시.. 찾아볼 예정.....
closes #270
> 270 로그인 uri 로직 수정 logout

- src/main/java/goorm/eagle7/stelligence/domain/notification/NotificationRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/NotificationService.java
- 이제 알림을 제공할 때에 최근에 발생할 알림 순으로 제공됩니다.
closes #297
> 297 알림을 제공할 때 최신순으로 제공

- src/main/java/goorm/eagle7/stelligence/common/auth/filter/AuthExceptionHandlerFilter.java
- src/main/java/goorm/eagle7/stelligence/common/auth/filter/AuthFilter.java
- src/main/java/goorm/eagle7/stelligence/common/auth/filter/handler/CustomAccessDeniedHandler.java
- src/main/java/goorm/eagle7/stelligence/common/auth/filter/handler/CustomAuthenticationEntryPoint.java
- src/main/java/goorm/eagle7/stelligence/common/auth/oauth/handler/OAuth2LoginFailureHandler.java
- src/main/java/goorm/eagle7/stelligence/common/auth/oauth/handler/OAuth2LoginSuccessHandler.java
- src/main/java/goorm/eagle7/stelligence/common/auth/oauth/handler/OAuth2LogoutSuccessHandler.java
- src/main/java/goorm/eagle7/stelligence/common/util/ResponseTemplateUtils.java
- 요구사항 변경으로 get, /api/members/me 는 권한 없는 경우 401 -> 403 변경
- 바로 응답 보내고 return 으로 구현
- 하드코딩으로 우선 진행,  추후 권한 관련 시큐리티 설정 리팩토링 예정. 
closes #305
> 305 요구사항 변경으로 membersme uri 권한 없는 경우 403으로 변경

- src/main/java/goorm/eagle7/stelligence/domain/notification/NotificationRepository.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/custom/CustomNotificationRepositoryImpl.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/dto/response/NotificationResponse.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/model/Notification.java
- src/main/java/goorm/eagle7/stelligence/domain/notification/model/NotificationContent.java
- src/main/resources/schema.sql
- src/test/java/goorm/eagle7/stelligence/domain/notification/NotificationRepositoryTest.java
- src/test/java/goorm/eagle7/stelligence/domain/notification/NotificationServiceTest.java
- src/test/java/goorm/eagle7/stelligence/domain/notification/TestNotificationContent.java
- src/test/resources/schema.sql
- 알림 테이블을 정규화하여 불필요한 중복을 제거합니다.
- 메인에 머지되기 전에 기존의 데이터 테이블을 변경하는 작업을 수행해야합니다.
closes #321
> 321 알림 테이블 정규화

- src/main/java/goorm/eagle7/stelligence/config/CorsConfig.java
- src/main/java/goorm/eagle7/stelligence/config/CorsProperties.java
- src/main/java/goorm/eagle7/stelligence/config/WebConfig.java
- 추후 cors 시 코드 수정 최소화 위해 yml으로 관리할 수 있도록 설정
- 지금 머지하는 게 위험 부담 있다면 그냥 reject하셔도 됩니다! 
- 통과한다면, application-local.yml, aplication-cors.yml 따로 슬랙에 공유하겠습니다~
closes #316
> 316 cors yml으로 관리

- src/main/java/goorm/eagle7/stelligence/config/SecurityConfig.java
- isPreFlightRequest 설정
- 
closes #331
> [#331] fix: security config에 cors isPreFlightRequest 설

- src/main/java/goorm/eagle7/stelligence/config/CorsConfig.java
- 프론트 주소 추가
- stelligence.site
- 아무도 없는 이때... 오류나면 수정할 수 있어서... 셀프 머지...... 시도...
- 오류나면 변경 예정...
closes #335
> [#335] refactor: cors 프론트 주소 추가 

- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeController.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/ContributeService.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/dto/ContributeDocumentPageResponse.java
- src/main/java/goorm/eagle7/stelligence/domain/contribute/dto/ContributeListByDocumentResponse.java
- 문서별 수정요청 목록 조회 시 필드에 documentId, documentTitle 추가
- 
closes #
> 320 contribute 문서 목록 조회 시 response 변경

- src/test/java/goorm/eagle7/stelligence/common/auth/jwt/JwtTokenReissueServiceTest.java
- src/test/java/goorm/eagle7/stelligence/common/auth/jwt/JwtTokenServiceTest.java
- 이전 pr 피드백 받은 내용 반영
- 변수명 및 test코드 반영되지 않았던 부분 수정
- .
closes #102
> 102 jwt test 코드 PR 이후 추가 수정

- src/main/java/goorm/eagle7/stelligence/domain/notification/listener/badge/NewBadgeNotifier.java
- src/test/java/goorm/eagle7/stelligence/domain/notification/listener/badge/NewBadgeNotifierTest.java
- 배지 획득시 사용자에게 알림을 전송합니다.
- 
closes #340
> 340 배지 획득시 알림 전송
